import { pgSchema, text, timestamp, bigserial, jsonb, inet, check, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Portal database schema — kept under the `portal` Postgres schema rather
 * than the default `public` schema so it's clearly separated from anything
 * Supabase auto-creates (Storage tables, auth tables, etc.).
 *
 * Source of truth for the structure: db/migrations/*.sql (generated by drizzle-kit).
 * Code that reads/writes should always go through the helpers in
 * src/lib/portal/db/ — never raw Supabase client calls in components.
 */

export const portal = pgSchema("portal");

// ───────────────────────────────────────────────────────────────────────────
// portal.users
// Clerk ↔ Salesforce link table. Single source of truth for "who is this
// portal user, which SF Account do they belong to". Replaces the
// `PORTAL_DEV_ACCOUNT_ID` dev hack.
// ───────────────────────────────────────────────────────────────────────────

export const portalUserStatus = ["pending", "active", "disabled"] as const;
export type PortalUserStatus = (typeof portalUserStatus)[number];

export const portalBrand = ["clever", "workwell"] as const;
export type PortalBrand = (typeof portalBrand)[number];

export const users = portal.table(
  "users",
  {
    clerkUserId: text("clerk_user_id").primaryKey(),
    contactSfId: text("contact_sf_id").notNull(),
    accountSfId: text("account_sf_id").notNull(),
    brand: text("brand").$type<PortalBrand>().notNull(),
    email: text("email").notNull(),
    status: text("status").$type<PortalUserStatus>().notNull(),
    invitedAt: timestamp("invited_at", { withTimezone: true }).notNull().defaultNow(),
    firstLoginAt: timestamp("first_login_at", { withTimezone: true }),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  },
  (t) => ({
    // Lower-case email enforcement — guards against duplicate users with
    // Mismatched-Case@example.com style addresses
    emailLowerCheck: check("users_email_lower", sql`${t.email} = lower(${t.email})`),
    // Lookup by email (Clerk webhook resolves an email → user row)
    emailIdx: uniqueIndex("users_email_idx").on(t.email),
    // Lookup by account (scope queries to a user's Salesforce Account)
    accountSfIdx: index("users_account_sf_idx").on(t.accountSfId),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.audit_log
// Forensic trail of every portal action. Append-only — used for GDPR Art. 32
// compliance, incident response, and dispute resolution.
// ───────────────────────────────────────────────────────────────────────────

export const auditLog = portal.table(
  "audit_log",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    clerkUserId: text("clerk_user_id"), // nullable: anonymous/pre-auth events have no user
    accountSfId: text("account_sf_id"),
    action: text("action").notNull(), // 'login' | 'view_dashboard' | 'view_el' | …
    target: text("target"),
    ip: inet("ip"),
    userAgent: text("user_agent"),
    metadata: jsonb("metadata"),
  },
  (t) => ({
    // Per-user activity history (newest first)
    userAtIdx: index("audit_log_user_at_idx").on(t.clerkUserId, t.at.desc()),
    // Per-account activity (useful for staff-side audit queries)
    accountAtIdx: index("audit_log_account_at_idx").on(t.accountSfId, t.at.desc()),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.push_tokens
// Placeholder for Phase 2 (Capacitor mobile + web push). Included now so
// migrations stay clean later. Empty until we wire push.
// ───────────────────────────────────────────────────────────────────────────

export const pushTokens = portal.table(
  "push_tokens",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    clerkUserId: text("clerk_user_id").notNull(),
    platform: text("platform").$type<"web" | "ios" | "android">().notNull(),
    token: text("token").notNull(),
    deviceName: text("device_name"),
    lastSeen: timestamp("last_seen", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // Lookup tokens for a user when fanning out a push notification
    userIdx: index("push_tokens_user_idx").on(t.clerkUserId),
    // Prevent duplicate registrations of the same token on the same user
    userTokenUq: uniqueIndex("push_tokens_user_token_uq").on(t.clerkUserId, t.token),
  })
);

// Convenient inferred types
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;
export type PushToken = typeof pushTokens.$inferSelect;
export type NewPushToken = typeof pushTokens.$inferInsert;
