import {
  pgSchema,
  text,
  timestamp,
  bigserial,
  jsonb,
  inet,
  integer,
  boolean,
  date,
  check,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Portal database schema — kept under the `portal` Postgres schema rather
 * than the default `public` schema so it's clearly separated from anything
 * Supabase auto-creates (Storage tables, auth tables, etc.).
 *
 * Source of truth for the structure: db/migrations/*.sql (generated by drizzle-kit).
 * Code that reads/writes should always go through the helpers in
 * src/lib/portal/db/ — never raw Supabase client calls in components.
 */

export const portal = pgSchema("portal");

// ───────────────────────────────────────────────────────────────────────────
// portal.users
// Clerk ↔ Salesforce link table. Single source of truth for "who is this
// portal user, which SF Account do they belong to". Replaces the
// `PORTAL_DEV_ACCOUNT_ID` dev hack.
// ───────────────────────────────────────────────────────────────────────────

export const portalUserStatus = ["pending", "active", "disabled"] as const;
export type PortalUserStatus = (typeof portalUserStatus)[number];

export const portalBrand = ["clever", "workwell"] as const;
export type PortalBrand = (typeof portalBrand)[number];

export const users = portal.table(
  "users",
  {
    clerkUserId: text("clerk_user_id").primaryKey(),
    contactSfId: text("contact_sf_id").notNull(),
    accountSfId: text("account_sf_id").notNull(),
    brand: text("brand").$type<PortalBrand>().notNull(),
    email: text("email").notNull(),
    /**
     * Profile name cached from the Clerk webhook payload — populated by
     * user.created / user.updated handlers. Lets server components render
     * "Hi {firstName}" without calling Clerk's API on every render
     * (~200-400ms saved per page render).
     */
    firstName: text("first_name"),
    lastName: text("last_name"),
    status: text("status").$type<PortalUserStatus>().notNull(),
    invitedAt: timestamp("invited_at", { withTimezone: true }).notNull().defaultNow(),
    firstLoginAt: timestamp("first_login_at", { withTimezone: true }),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  },
  (t) => ({
    // Lower-case email enforcement — guards against duplicate users with
    // Mismatched-Case@example.com style addresses
    emailLowerCheck: check("users_email_lower", sql`${t.email} = lower(${t.email})`),
    // Lookup by email (Clerk webhook resolves an email → user row)
    emailIdx: uniqueIndex("users_email_idx").on(t.email),
    // Lookup by account (scope queries to a user's Salesforce Account)
    accountSfIdx: index("users_account_sf_idx").on(t.accountSfId),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.audit_log
// Forensic trail of every portal action. Append-only — used for GDPR Art. 32
// compliance, incident response, and dispute resolution.
// ───────────────────────────────────────────────────────────────────────────

export const auditLog = portal.table(
  "audit_log",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    clerkUserId: text("clerk_user_id"), // nullable: anonymous/pre-auth events have no user
    accountSfId: text("account_sf_id"),
    action: text("action").notNull(), // 'login' | 'view_dashboard' | 'view_el' | …
    target: text("target"),
    ip: inet("ip"),
    userAgent: text("user_agent"),
    metadata: jsonb("metadata"),
  },
  (t) => ({
    // Per-user activity history (newest first)
    userAtIdx: index("audit_log_user_at_idx").on(t.clerkUserId, t.at.desc()),
    // Per-account activity (useful for staff-side audit queries)
    accountAtIdx: index("audit_log_account_at_idx").on(t.accountSfId, t.at.desc()),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.push_tokens
// Placeholder for Phase 2 (Capacitor mobile + web push). Included now so
// migrations stay clean later. Empty until we wire push.
// ───────────────────────────────────────────────────────────────────────────

export const pushTokens = portal.table(
  "push_tokens",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    clerkUserId: text("clerk_user_id").notNull(),
    platform: text("platform").$type<"web" | "ios" | "android">().notNull(),
    token: text("token").notNull(),
    deviceName: text("device_name"),
    lastSeen: timestamp("last_seen", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // Lookup tokens for a user when fanning out a push notification
    userIdx: index("push_tokens_user_idx").on(t.clerkUserId),
    // Prevent duplicate registrations of the same token on the same user
    userTokenUq: uniqueIndex("push_tokens_user_token_uq").on(t.clerkUserId, t.token),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// Salesforce read cache (Stage 3, 2026-05-11)
//
// Mirrors a curated slice of SF data so portal page renders don't have to
// hit the SF REST API on every request. Population path:
//
//   SF trigger → Portal_Sync_Event__e → subscriber Apex → outbound HTTPS
//   callout (HMAC-signed) → /api/portal/sync → upsert into these tables
//
// Latency: typically 2-5 seconds from SF change to portal-visible. The
// user signed off on this trade-off when we agreed Stage 3 over keeping
// real-time SF reads ("real-time emails not needed").
//
// What we DON'T cache:
//   - Anything not directly used by the portal — keeps blast radius small
//     and avoids GDPR over-retention.
//   - The full row — we keep only the fields the portal renders or filters
//     by. `raw` jsonb holds the verbatim event payload for debug.
//
// All cached tables share the convention:
//   sf_id        — SF 18-char id, primary key
//   account_sf_id — denormalised for fast WHERE on portal queries
//   updated_at   — when our cache row last changed (UTC, set by sync)
//   sf_updated_at — SF's LastModifiedDate (for drift detection)
//   raw          — full event payload, for forensic debugging
// ───────────────────────────────────────────────────────────────────────────

// portal.accounts ─── cached SF Account (the firm / client entity)
export const accounts = portal.table(
  "accounts",
  {
    sfId: text("sf_id").primaryKey(),
    name: text("name").notNull(),
    brand: text("brand").$type<PortalBrand>().notNull(),
    /** SF User id of the assigned accountant (Account.OwnerId). */
    ownerSfId: text("owner_sf_id"),
    /** Inactive accounts hide from the portal but stay cached for audit. */
    active: boolean("active").notNull().default(true),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    brandIdx: index("accounts_brand_idx").on(t.brand),
    ownerIdx: index("accounts_owner_idx").on(t.ownerSfId),
  })
);

// portal.contacts ─── cached SF Contact (the individual person)
export const contacts = portal.table(
  "contacts",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    email: text("email"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    phone: text("phone"),
    isPrimary: boolean("is_primary").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("contacts_account_idx").on(t.accountSfId),
    emailIdx: index("contacts_email_idx").on(t.email),
  })
);

// portal.workflows ─── cached New_Client_Workflow__c (onboarding state)
export const workflows = portal.table(
  "workflows",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    /** One of welcome / main / portal / checkin30 / checkin60 / catchup / complete. */
    currentStage: text("current_stage").notNull(),
    stageNumber: integer("stage_number").notNull(),
    /** 'client' | 'us' | 'nobody' — who is the bottleneck. */
    blockedOn: text("blocked_on").notNull(),
    /** 'on_track' | 'due_soon' | 'overdue' — derived SLA status. */
    slaStatus: text("sla_status").notNull(),
    signedOffAt: date("signed_off_at"),
    // Per-stage milestone fields — denormalised for the dashboard stepper
    welcomeCompleteAt: date("welcome_complete_at"),
    welcomeDueAt: timestamp("welcome_due_at", { withTimezone: true }),
    welcomeScheduledAt: timestamp("welcome_scheduled_at", { withTimezone: true }),
    mainCompleteAt: date("main_complete_at"),
    mainDueAt: timestamp("main_due_at", { withTimezone: true }),
    mainScheduledAt: timestamp("main_scheduled_at", { withTimezone: true }),
    portalCompleteAt: date("portal_complete_at"),
    portalDueAt: timestamp("portal_due_at", { withTimezone: true }),
    portalScheduledAt: timestamp("portal_scheduled_at", { withTimezone: true }),
    catchupCompleteAt: date("catchup_complete_at"),
    catchupDueAt: timestamp("catchup_due_at", { withTimezone: true }),
    catchupScheduledAt: timestamp("catchup_scheduled_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("workflows_account_idx").on(t.accountSfId),
    activeIdx: index("workflows_active_idx").on(t.accountSfId, t.signedOffAt),
  })
);

// portal.engagement_letters ─── cached Engagement_Letter__c
export const engagementLetters = portal.table(
  "engagement_letters",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    /** 'Draft' | 'Sent' | 'Viewed' | 'Signed' | 'Cancelled' | 'Superseded'. */
    status: text("status").notNull(),
    variant: text("variant"),
    /** Public token for the email signing link (still used as fallback). */
    token: text("token"),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    firstViewedAt: timestamp("first_viewed_at", { withTimezone: true }),
    signedAt: timestamp("signed_at", { withTimezone: true }),
    signerName: text("signer_name"),
    signerEmail: text("signer_email"),
    /** True when Signed_PDF_Id__c is non-null (PDF available for download). */
    pdfReady: boolean("pdf_ready").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("engagement_letters_account_idx").on(t.accountSfId),
    // Portal shows the most recent non-cancelled letter — index supports it
    accountStatusIdx: index("engagement_letters_account_status_idx").on(
      t.accountSfId,
      t.status
    ),
  })
);

// portal.cases ─── cached Case (only Origin='Portal' rows are synced)
export const cases = portal.table(
  "cases",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    contactSfId: text("contact_sf_id"),
    /** 'New' | 'Working' | 'Closed' | etc. — SF standard Case statuses. */
    status: text("status").notNull(),
    subject: text("subject"),
    /** Portal-relevant boolean derived from IsClosed. */
    isClosed: boolean("is_closed").notNull().default(false),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("cases_account_idx").on(t.accountSfId),
    openIdx: index("cases_open_idx").on(t.accountSfId, t.isClosed),
  })
);

// portal.email_messages ─── cached EmailMessage children of portal Cases
export const emailMessages = portal.table(
  "email_messages",
  {
    sfId: text("sf_id").primaryKey(),
    caseSfId: text("case_sf_id").notNull(),
    /** Denormalised from the parent Case for fast portal queries. */
    accountSfId: text("account_sf_id").notNull(),
    fromAddress: text("from_address"),
    fromName: text("from_name"),
    subject: text("subject"),
    bodyText: text("body_text"),
    sentAt: timestamp("sent_at", { withTimezone: true }).notNull(),
    /** True when the message came from the client (portal-authored). */
    isFromClient: boolean("is_from_client").notNull().default(false),
    /** True when sent via the portal (vs. inbound from staff email). */
    isPortalAuthored: boolean("is_portal_authored").notNull().default(false),
    /** Staff-side checkbox to hide a message from the portal. */
    hideFromPortal: boolean("hide_from_portal").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    // Primary access pattern: "show me this account's messages, newest first"
    accountSentIdx: index("email_messages_account_sent_idx").on(
      t.accountSfId,
      t.sentAt.desc()
    ),
    caseIdx: index("email_messages_case_idx").on(t.caseSfId),
  })
);

// portal.accountants ─── cached User profile of assigned accountants
// Strictly the fields the portal renders — never the entire User row.
export const accountants = portal.table(
  "accountants",
  {
    sfId: text("sf_id").primaryKey(), // User.Id
    name: text("name"),
    email: text("email"),
    /** SF UserId_short__c field — used to build the Calendly booking URL. */
    calendlySlug: text("calendly_slug"),
    photoUrl: text("photo_url"),
    /** Inactive accountants stay cached for historical records; portal hides them. */
    active: boolean("active").notNull().default(true),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  }
);

// ───────────────────────────────────────────────────────────────────────────
// portal.sync_log
// Forensic + ops trail for cache updates. One row per inbound sync event.
// Lets us answer "when did account X last sync, and from which SF object?"
// without re-reading the audit_log table.
// ───────────────────────────────────────────────────────────────────────────

export const syncLog = portal.table(
  "sync_log",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    /** 'Account' | 'Contact' | 'Case' | 'EmailMessage' | 'Engagement_Letter__c' | … */
    objectType: text("object_type").notNull(),
    sfId: text("sf_id").notNull(),
    /** 'UPSERT' | 'DELETE' | 'IGNORED_NOT_PORTAL' (Case/EmailMessage not Origin=Portal). */
    operation: text("operation").notNull(),
    /** 'success' | 'error'. */
    status: text("status").notNull(),
    /** Set only when status='error'. */
    errorMessage: text("error_message"),
    /** Lag in milliseconds from SF event to Postgres write. */
    latencyMs: integer("latency_ms"),
  },
  (t) => ({
    objectIdx: index("sync_log_object_idx").on(t.objectType, t.sfId, t.at.desc()),
    statusAtIdx: index("sync_log_status_at_idx").on(t.status, t.at.desc()),
  })
);

// Convenient inferred types
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;
export type PushToken = typeof pushTokens.$inferSelect;
export type NewPushToken = typeof pushTokens.$inferInsert;

// Cache types
export type CachedAccount = typeof accounts.$inferSelect;
export type NewCachedAccount = typeof accounts.$inferInsert;
export type CachedContact = typeof contacts.$inferSelect;
export type NewCachedContact = typeof contacts.$inferInsert;
export type CachedWorkflow = typeof workflows.$inferSelect;
export type NewCachedWorkflow = typeof workflows.$inferInsert;
export type CachedEngagementLetter = typeof engagementLetters.$inferSelect;
export type NewCachedEngagementLetter = typeof engagementLetters.$inferInsert;
export type CachedCase = typeof cases.$inferSelect;
export type NewCachedCase = typeof cases.$inferInsert;
export type CachedEmailMessage = typeof emailMessages.$inferSelect;
export type NewCachedEmailMessage = typeof emailMessages.$inferInsert;
export type CachedAccountant = typeof accountants.$inferSelect;
export type NewCachedAccountant = typeof accountants.$inferInsert;
export type SyncLogEntry = typeof syncLog.$inferSelect;
export type NewSyncLogEntry = typeof syncLog.$inferInsert;
