import {
  pgSchema,
  text,
  timestamp,
  bigserial,
  bigint,
  jsonb,
  inet,
  integer,
  boolean,
  date,
  check,
  index,
  uniqueIndex,
  primaryKey,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Portal database schema — kept under the `portal` Postgres schema rather
 * than the default `public` schema so it's clearly separated from anything
 * Supabase auto-creates (Storage tables, auth tables, etc.).
 *
 * Source of truth for the structure: db/migrations/*.sql (generated by drizzle-kit).
 * Code that reads/writes should always go through the helpers in
 * src/lib/portal/db/ — never raw Supabase client calls in components.
 */

export const portal = pgSchema("portal");

// ───────────────────────────────────────────────────────────────────────────
// portal.users
// Clerk IDENTITY row — one per Clerk user (i.e. per human login). Carries the
// profile (email, name) and the "active account" cursor pointing at whichever
// company the user is currently viewing.
//
// The account/contact/brand/status columns below are RETAINED for the
// dual-write transition to the membership model (portal.memberships). They
// mirror the user's *active* membership so existing read paths keep working
// unchanged; a later migration drops them once every reader goes through
// portal.memberships. New code should NOT read these — resolve the active
// membership instead.
// ───────────────────────────────────────────────────────────────────────────

export const portalUserStatus = ["pending", "active", "disabled"] as const;
export type PortalUserStatus = (typeof portalUserStatus)[number];

export const portalBrand = ["clever", "workwell"] as const;
export type PortalBrand = (typeof portalBrand)[number];

export const users = portal.table(
  "users",
  {
    clerkUserId: text("clerk_user_id").primaryKey(),
    contactSfId: text("contact_sf_id").notNull(),
    accountSfId: text("account_sf_id").notNull(),
    brand: text("brand").$type<PortalBrand>().notNull(),
    email: text("email").notNull(),
    /**
     * Profile name cached from the Clerk webhook payload — populated by
     * user.created / user.updated handlers. Lets server components render
     * "Hi {firstName}" without calling Clerk's API on every render
     * (~200-400ms saved per page render).
     */
    firstName: text("first_name"),
    lastName: text("last_name"),
    status: text("status").$type<PortalUserStatus>().notNull(),
    /**
     * The company the user is currently viewing — the "cursor" for the account
     * switcher. MUST always be validated against portal.memberships before use
     * (a stale/forged value must never grant scope). Null falls back to the
     * user's first active membership. See withPortalScope().
     */
    activeAccountSfId: text("active_account_sf_id"),
    invitedAt: timestamp("invited_at", { withTimezone: true }).notNull().defaultNow(),
    firstLoginAt: timestamp("first_login_at", { withTimezone: true }),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  },
  (t) => ({
    // Lower-case email enforcement — guards against duplicate users with
    // Mismatched-Case@example.com style addresses
    emailLowerCheck: check("users_email_lower", sql`${t.email} = lower(${t.email})`),
    // Lookup by email (Clerk webhook resolves an email → user row)
    emailIdx: uniqueIndex("users_email_idx").on(t.email),
    // Lookup by account (scope queries to a user's Salesforce Account)
    accountSfIdx: index("users_account_sf_idx").on(t.accountSfId),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.memberships
// One row per (Clerk user, Salesforce Account) — the many-to-many join that
// lets a single login access multiple companies (e.g. a director of two Ltd
// companies, both clients of the same brand). Status is PER-COMPANY: a user
// can be 'active' on one company and 'pending' on another.
//
// Brand lives here (a property of the company, not the person). Cross-brand
// membership is out of scope — the two brands run separate Clerk instances,
// so a login only ever spans companies within one brand.
//
// This is the authorization source of truth for the account switcher: the
// active account is only ever honoured if the caller holds a matching row
// here. See withPortalScope() / setActiveAccount().
// ───────────────────────────────────────────────────────────────────────────

export const memberships = portal.table(
  "memberships",
  {
    clerkUserId: text("clerk_user_id").notNull(),
    accountSfId: text("account_sf_id").notNull(),
    contactSfId: text("contact_sf_id").notNull(),
    brand: text("brand").$type<PortalBrand>().notNull(),
    /** Per-company access state — same vocabulary as portal.users.status. */
    status: text("status").$type<PortalUserStatus>().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // A user holds at most one membership per company.
    pk: primaryKey({ columns: [t.clerkUserId, t.accountSfId] }),
    // List all companies a user can access (drives the switcher).
    userIdx: index("memberships_user_idx").on(t.clerkUserId),
    // Reverse lookup: who can access this company (staff/audit queries).
    accountIdx: index("memberships_account_idx").on(t.accountSfId),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.audit_log
// Forensic trail of every portal action. Append-only — used for GDPR Art. 32
// compliance, incident response, and dispute resolution.
// ───────────────────────────────────────────────────────────────────────────

export const auditLog = portal.table(
  "audit_log",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    clerkUserId: text("clerk_user_id"), // nullable: anonymous/pre-auth events have no user
    accountSfId: text("account_sf_id"),
    action: text("action").notNull(), // 'login' | 'view_dashboard' | 'view_el' | …
    target: text("target"),
    ip: inet("ip"),
    userAgent: text("user_agent"),
    metadata: jsonb("metadata"),
  },
  (t) => ({
    // Per-user activity history (newest first)
    userAtIdx: index("audit_log_user_at_idx").on(t.clerkUserId, t.at.desc()),
    // Per-account activity (useful for staff-side audit queries)
    accountAtIdx: index("audit_log_account_at_idx").on(t.accountSfId, t.at.desc()),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.push_tokens
// Placeholder for Phase 2 (Capacitor mobile + web push). Included now so
// migrations stay clean later. Empty until we wire push.
// ───────────────────────────────────────────────────────────────────────────

export const pushTokens = portal.table(
  "push_tokens",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    clerkUserId: text("clerk_user_id").notNull(),
    platform: text("platform").$type<"web" | "ios" | "android">().notNull(),
    token: text("token").notNull(),
    deviceName: text("device_name"),
    lastSeen: timestamp("last_seen", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // Lookup tokens for a user when fanning out a push notification
    userIdx: index("push_tokens_user_idx").on(t.clerkUserId),
    // Prevent duplicate registrations of the same token on the same user
    userTokenUq: uniqueIndex("push_tokens_user_token_uq").on(t.clerkUserId, t.token),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// Salesforce read cache (Stage 3, 2026-05-11)
//
// Mirrors a curated slice of SF data so portal page renders don't have to
// hit the SF REST API on every request. Population path:
//
//   SF trigger → Portal_Sync_Event__e → subscriber Apex → outbound HTTPS
//   callout (HMAC-signed) → /api/portal/sync → upsert into these tables
//
// Latency: typically 2-5 seconds from SF change to portal-visible. The
// user signed off on this trade-off when we agreed Stage 3 over keeping
// real-time SF reads ("real-time emails not needed").
//
// What we DON'T cache:
//   - Anything not directly used by the portal — keeps blast radius small
//     and avoids GDPR over-retention.
//   - The full row — we keep only the fields the portal renders or filters
//     by. `raw` jsonb holds the verbatim event payload for debug.
//
// All cached tables share the convention:
//   sf_id        — SF 18-char id, primary key
//   account_sf_id — denormalised for fast WHERE on portal queries
//   updated_at   — when our cache row last changed (UTC, set by sync)
//   sf_updated_at — SF's LastModifiedDate (for drift detection)
//   raw          — full event payload, for forensic debugging
// ───────────────────────────────────────────────────────────────────────────

// portal.accounts ─── cached SF Account (the firm / client entity)
export const accounts = portal.table(
  "accounts",
  {
    sfId: text("sf_id").primaryKey(),
    name: text("name").notNull(),
    brand: text("brand").$type<PortalBrand>().notNull(),
    /** SF User id of the assigned accountant (Account.OwnerId). */
    ownerSfId: text("owner_sf_id"),
    /** Inactive accounts hide from the portal but stay cached for audit. */
    active: boolean("active").notNull().default(true),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    brandIdx: index("accounts_brand_idx").on(t.brand),
    ownerIdx: index("accounts_owner_idx").on(t.ownerSfId),
  })
);

// portal.contacts ─── cached SF Contact (the individual person)
export const contacts = portal.table(
  "contacts",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    email: text("email"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    phone: text("phone"),
    isPrimary: boolean("is_primary").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("contacts_account_idx").on(t.accountSfId),
    emailIdx: index("contacts_email_idx").on(t.email),
  })
);

// portal.workflows ─── cached New_Client_Workflow__c (onboarding state)
export const workflows = portal.table(
  "workflows",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    /** One of welcome / main / portal / checkin30 / checkin60 / catchup / complete. */
    currentStage: text("current_stage").notNull(),
    stageNumber: integer("stage_number").notNull(),
    /** 'client' | 'us' | 'nobody' — who is the bottleneck. */
    blockedOn: text("blocked_on").notNull(),
    /** 'on_track' | 'due_soon' | 'overdue' — derived SLA status. */
    slaStatus: text("sla_status").notNull(),
    signedOffAt: date("signed_off_at"),
    // Per-stage milestone fields — denormalised for the dashboard stepper
    welcomeCompleteAt: date("welcome_complete_at"),
    welcomeDueAt: timestamp("welcome_due_at", { withTimezone: true }),
    welcomeScheduledAt: timestamp("welcome_scheduled_at", { withTimezone: true }),
    mainCompleteAt: date("main_complete_at"),
    mainDueAt: timestamp("main_due_at", { withTimezone: true }),
    mainScheduledAt: timestamp("main_scheduled_at", { withTimezone: true }),
    portalCompleteAt: date("portal_complete_at"),
    portalDueAt: timestamp("portal_due_at", { withTimezone: true }),
    portalScheduledAt: timestamp("portal_scheduled_at", { withTimezone: true }),
    catchupCompleteAt: date("catchup_complete_at"),
    catchupDueAt: timestamp("catchup_due_at", { withTimezone: true }),
    catchupScheduledAt: timestamp("catchup_scheduled_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("workflows_account_idx").on(t.accountSfId),
    activeIdx: index("workflows_active_idx").on(t.accountSfId, t.signedOffAt),
  })
);

// portal.engagement_letters ─── cached Engagement_Letter__c
export const engagementLetters = portal.table(
  "engagement_letters",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    /** 'Draft' | 'Sent' | 'Viewed' | 'Signed' | 'Cancelled' | 'Superseded'. */
    status: text("status").notNull(),
    variant: text("variant"),
    /** Public token for the email signing link (still used as fallback). */
    token: text("token"),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    firstViewedAt: timestamp("first_viewed_at", { withTimezone: true }),
    signedAt: timestamp("signed_at", { withTimezone: true }),
    signerName: text("signer_name"),
    signerEmail: text("signer_email"),
    /** True when Signed_PDF_Id__c is non-null (PDF available for download). */
    pdfReady: boolean("pdf_ready").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("engagement_letters_account_idx").on(t.accountSfId),
    // Portal shows the most recent non-cancelled letter — index supports it
    accountStatusIdx: index("engagement_letters_account_status_idx").on(
      t.accountSfId,
      t.status
    ),
  })
);

// portal.cases ─── cached Case (only Origin='Portal' rows are synced)
export const cases = portal.table(
  "cases",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    contactSfId: text("contact_sf_id"),
    /** 'New' | 'Working' | 'Closed' | etc. — SF standard Case statuses. */
    status: text("status").notNull(),
    subject: text("subject"),
    /** Portal-relevant boolean derived from IsClosed. */
    isClosed: boolean("is_closed").notNull().default(false),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("cases_account_idx").on(t.accountSfId),
    openIdx: index("cases_open_idx").on(t.accountSfId, t.isClosed),
  })
);

// portal.email_messages ─── cached EmailMessage children of portal Cases
export const emailMessages = portal.table(
  "email_messages",
  {
    sfId: text("sf_id").primaryKey(),
    caseSfId: text("case_sf_id").notNull(),
    /** Denormalised from the parent Case for fast portal queries. */
    accountSfId: text("account_sf_id").notNull(),
    fromAddress: text("from_address"),
    fromName: text("from_name"),
    subject: text("subject"),
    bodyText: text("body_text"),
    sentAt: timestamp("sent_at", { withTimezone: true }).notNull(),
    /** True when the message came from the client (portal-authored). */
    isFromClient: boolean("is_from_client").notNull().default(false),
    /** True when sent via the portal (vs. inbound from staff email). */
    isPortalAuthored: boolean("is_portal_authored").notNull().default(false),
    /** Staff-side checkbox to hide a message from the portal. */
    hideFromPortal: boolean("hide_from_portal").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    // Primary access pattern: "show me this account's messages, newest first"
    accountSentIdx: index("email_messages_account_sent_idx").on(
      t.accountSfId,
      t.sentAt.desc()
    ),
    caseIdx: index("email_messages_case_idx").on(t.caseSfId),
  })
);

// portal.accountants ─── cached User profile of assigned accountants
// Strictly the fields the portal renders — never the entire User row.
export const accountants = portal.table(
  "accountants",
  {
    sfId: text("sf_id").primaryKey(), // User.Id
    name: text("name"),
    email: text("email"),
    /** SF UserId_short__c field — used to build the Calendly booking URL. */
    calendlySlug: text("calendly_slug"),
    photoUrl: text("photo_url"),
    /** Inactive accountants stay cached for historical records; portal hides them. */
    active: boolean("active").notNull().default(true),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  }
);

// portal.companies ─── cached CH_Company__c (Companies House company record)
// One per Account (Account.CH_Company__c lookup). Synced from Companies House
// via CompaniesHouseSyncBatch on the SF side; mirrored here for the portal
// "Your details" page.
export const companies = portal.table(
  "companies",
  {
    sfId: text("sf_id").primaryKey(), // CH_Company__c.Id
    accountSfId: text("account_sf_id").notNull(),
    companyNumber: text("company_number"),
    companyName: text("company_name"),
    status: text("status"), // 'active' | 'liquidation' | …
    statusDetail: text("status_detail"),
    companyType: text("company_type"), // 'private-limited' | 'plc' | …
    dateOfCreation: date("date_of_creation"),
    dateOfCessation: date("date_of_cessation"),
    // Registered office address
    regPremises: text("reg_premises"),
    regLine1: text("reg_line_1"),
    regLine2: text("reg_line_2"),
    regLocality: text("reg_locality"),
    regRegion: text("reg_region"),
    regPostalCode: text("reg_postal_code"),
    regCountry: text("reg_country"),
    sicCodes: text("sic_codes"),
    // Filing deadlines
    accountsNextDue: date("accounts_next_due"),
    accountsLastMadeUp: date("accounts_last_made_up"),
    accountsNextPeriodEnd: date("accounts_next_period_end"),
    accountsOverdue: boolean("accounts_overdue").notNull().default(false),
    csNextDue: date("cs_next_due"),
    csLastMadeUp: date("cs_last_made_up"),
    csOverdue: boolean("cs_overdue").notNull().default(false),
    lastSynced: timestamp("last_synced", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("companies_account_idx").on(t.accountSfId),
  })
);

// portal.officers ─── cached CH_Officer__c (directors / secretaries) flattened
// with their CH_Company_Officer__c appointment. account_sf_id is denormalised
// so the portal can scope-filter without joining through the company.
export const officers = portal.table(
  "officers",
  {
    sfId: text("sf_id").primaryKey(), // CH_Officer__c.Id
    accountSfId: text("account_sf_id").notNull(),
    companySfId: text("company_sf_id"),
    name: text("name"),
    officerRole: text("officer_role"), // 'director' | 'secretary' | …
    appointedOn: date("appointed_on"),
    resignedOn: date("resigned_on"), // null = active
    monthOfBirth: text("month_of_birth"),
    yearOfBirth: text("year_of_birth"),
    occupation: text("occupation"),
    nationality: text("nationality"),
    countryOfResidence: text("country_of_residence"),
    addrPremises: text("addr_premises"),
    addrLine1: text("addr_line_1"),
    addrLine2: text("addr_line_2"),
    addrLocality: text("addr_locality"),
    addrRegion: text("addr_region"),
    addrPostalCode: text("addr_postal_code"),
    addrCountry: text("addr_country"),
    idvVerifiedOn: date("idv_verified_on"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountIdx: index("officers_account_idx").on(t.accountSfId),
    companyIdx: index("officers_company_idx").on(t.companySfId),
  })
);

// portal.deadlines ─── upcoming statutory + filing deadlines for an Account.
// Aggregates CH dates (accounts / confirmation statement) plus VAT, Self
// Assessment, Corporation Tax and payroll dates from Salesforce. The single
// biggest reason a client logs in: "what's due and when".
export const deadlines = portal.table(
  "deadlines",
  {
    sfId: text("sf_id").primaryKey(), // source record id (or synthetic key)
    accountSfId: text("account_sf_id").notNull(),
    /** 'accounts' | 'confirmation_statement' | 'vat' | 'self_assessment' | 'corporation_tax' | 'payroll' */
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    dueDate: date("due_date"),
    periodLabel: text("period_label"),
    /** 'upcoming' | 'due_soon' | 'overdue' | 'submitted' */
    status: text("status").notNull(),
    /** 'client' | 'us' | 'nobody' — who needs to act next. */
    blockedOn: text("blocked_on"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountDueIdx: index("deadlines_account_due_idx").on(t.accountSfId, t.dueDate),
  })
);

// portal.notifications ─── the retention backbone. Every actionable event
// (new reply, deadline approaching, item to approve, document ready, info
// requested) becomes a row here, deep-linking into the relevant surface.
// Drives the sidebar bell + the /portal/notifications inbox.
export const notifications = portal.table(
  "notifications",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    /** Source Notification__c id. The sync upsert key. NULL for legacy seeded rows. */
    sfId: text("sf_id"),
    accountSfId: text("account_sf_id").notNull(),
    /** 'message' | 'deadline' | 'approval' | 'request' | 'document' | 'general' */
    type: text("type").notNull(),
    title: text("title").notNull(),
    body: text("body"),
    /** Deep link into the portal (e.g. /portal/deadlines). */
    href: text("href"),
    /** True when the client must DO something (approve, sign, send) vs FYI. */
    actionRequired: boolean("action_required").notNull().default(false),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
  },
  (t) => ({
    accountCreatedIdx: index("notifications_account_created_idx").on(
      t.accountSfId,
      t.createdAt.desc()
    ),
    accountUnreadIdx: index("notifications_account_unread_idx").on(
      t.accountSfId,
      t.readAt
    ),
    // Idempotency key for the SF→cache sync (ON CONFLICT target). NULLs are
    // distinct in Postgres, so legacy seeded rows (sf_id NULL) don't collide.
    sfIdUq: uniqueIndex("notifications_sf_id_uq").on(t.sfId),
  })
);

// portal.approvals ─── items awaiting the client's sign-off (MTD quarterly
// review, VAT return, Self Assessment, year-end accounts). The portal's
// "approve / sign" surface. Writes (approve) go SF-direct in prod (MTDApproval
// service etc.) then sync back; cached here for the read + a fast optimistic
// status flip.
export const approvals = portal.table(
  "approvals",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    /** 'mtd_review' | 'vat' | 'self_assessment' | 'accounts' */
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    periodLabel: text("period_label"),
    /** 'pending' | 'approved' | 'queried' */
    status: text("status").notNull(),
    summary: text("summary"),
    /** Short headline figure, e.g. "£4,210.50 due to HMRC". */
    amountLabel: text("amount_label"),
    dueDate: date("due_date"),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountStatusIdx: index("approvals_account_status_idx").on(
      t.accountSfId,
      t.status
    ),
  })
);

// portal.documents ─── file exchange. Two directions:
//   'shared'  — a file we've produced for the client to DOWNLOAD (accounts,
//               VAT return, payslip, signed engagement letter, …)
//   'request' — a file we NEED the client to UPLOAD (photo ID, proof of
//               address, last year's tax return, …); status requested|received
// Backed in prod by SF ContentDocument/ContentVersion; cached here for the list.
export const documents = portal.table(
  "documents",
  {
    sfId: text("sf_id").primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    name: text("name").notNull(),
    /** 'accounts' | 'vat' | 'tax_return' | 'payslip' | 'p60' | 'engagement_letter' | 'identity' | 'proof_of_address' | 'other' */
    category: text("category").notNull(),
    /** 'shared' (downloadable) | 'request' (we need it uploaded) */
    direction: text("direction").notNull(),
    /** shared → 'available'; request → 'requested' | 'received' */
    status: text("status").notNull(),
    fileType: text("file_type"),
    sizeLabel: text("size_label"),
    /** Download link (shared docs) — proxied via SF in prod. */
    downloadUrl: text("download_url"),
    /** When shared, or when an upload was received. */
    sharedAt: timestamp("shared_at", { withTimezone: true }),
    /** For requests — when we'd like it by. */
    dueDate: date("due_date"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    sfUpdatedAt: timestamp("sf_updated_at", { withTimezone: true }),
    raw: jsonb("raw"),
  },
  (t) => ({
    accountDirIdx: index("documents_account_dir_idx").on(
      t.accountSfId,
      t.direction
    ),
  })
);

// portal.document_uploads ─── client-initiated uploads (client → us).
// Portal-NATIVE (not an SF mirror): the client sends 1+ files plus a note
// describing what they are. File bytes live in a private Supabase Storage
// bucket; this row carries the commentary + status; `sf_content_ref` holds the
// Salesforce reference once the batch has been pushed across so staff see it.
export const documentUploads = portal.table(
  "document_uploads",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    accountSfId: text("account_sf_id").notNull(),
    /** Clerk user + SF Contact who uploaded — for audit + staff context. */
    clerkUserId: text("clerk_user_id"),
    contactSfId: text("contact_sf_id"),
    /** Client's free-text commentary — "what is this?". */
    note: text("note"),
    /**
     * 'pending'  — row created, files not yet confirmed uploaded
     * 'received' — files in Supabase Storage, visible in the portal history
     * 'pushed'   — mirrored into Salesforce (sf_content_ref set)
     * 'push_failed' — in Supabase but the SF push errored (retryable)
     */
    status: text("status").notNull().default("pending"),
    sfContentRef: text("sf_content_ref"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    accountCreatedIdx: index("document_uploads_account_created_idx").on(
      t.accountSfId,
      t.createdAt.desc()
    ),
  })
);

// portal.document_upload_files ─── the individual files within one upload batch.
export const documentUploadFiles = portal.table(
  "document_upload_files",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    uploadId: bigint("upload_id", { mode: "number" }).notNull(),
    fileName: text("file_name").notNull(),
    fileType: text("file_type"),
    sizeBytes: integer("size_bytes"),
    /** Object path within the private `portal-uploads` Storage bucket. */
    storagePath: text("storage_path").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uploadIdx: index("document_upload_files_upload_idx").on(t.uploadId),
  })
);

// ───────────────────────────────────────────────────────────────────────────
// portal.sync_log
// Forensic + ops trail for cache updates. One row per inbound sync event.
// Lets us answer "when did account X last sync, and from which SF object?"
// without re-reading the audit_log table.
// ───────────────────────────────────────────────────────────────────────────

export const syncLog = portal.table(
  "sync_log",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    /** 'Account' | 'Contact' | 'Case' | 'EmailMessage' | 'Engagement_Letter__c' | … */
    objectType: text("object_type").notNull(),
    sfId: text("sf_id").notNull(),
    /** 'UPSERT' | 'DELETE' | 'IGNORED_NOT_PORTAL' (Case/EmailMessage not Origin=Portal). */
    operation: text("operation").notNull(),
    /** 'success' | 'error'. */
    status: text("status").notNull(),
    /** Set only when status='error'. */
    errorMessage: text("error_message"),
    /** Lag in milliseconds from SF event to Postgres write. */
    latencyMs: integer("latency_ms"),
  },
  (t) => ({
    objectIdx: index("sync_log_object_idx").on(t.objectType, t.sfId, t.at.desc()),
    statusAtIdx: index("sync_log_status_at_idx").on(t.status, t.at.desc()),
  })
);

// Convenient inferred types
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Membership = typeof memberships.$inferSelect;
export type NewMembership = typeof memberships.$inferInsert;
export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;
export type PushToken = typeof pushTokens.$inferSelect;
export type NewPushToken = typeof pushTokens.$inferInsert;

// Cache types
export type CachedAccount = typeof accounts.$inferSelect;
export type NewCachedAccount = typeof accounts.$inferInsert;
export type CachedContact = typeof contacts.$inferSelect;
export type NewCachedContact = typeof contacts.$inferInsert;
export type CachedWorkflow = typeof workflows.$inferSelect;
export type NewCachedWorkflow = typeof workflows.$inferInsert;
export type CachedEngagementLetter = typeof engagementLetters.$inferSelect;
export type NewCachedEngagementLetter = typeof engagementLetters.$inferInsert;
export type CachedCase = typeof cases.$inferSelect;
export type NewCachedCase = typeof cases.$inferInsert;
export type CachedEmailMessage = typeof emailMessages.$inferSelect;
export type NewCachedEmailMessage = typeof emailMessages.$inferInsert;
export type CachedAccountant = typeof accountants.$inferSelect;
export type NewCachedAccountant = typeof accountants.$inferInsert;
export type SyncLogEntry = typeof syncLog.$inferSelect;
export type NewSyncLogEntry = typeof syncLog.$inferInsert;
export type CachedCompany = typeof companies.$inferSelect;
export type NewCachedCompany = typeof companies.$inferInsert;
export type CachedOfficer = typeof officers.$inferSelect;
export type NewCachedOfficer = typeof officers.$inferInsert;
export type CachedDeadline = typeof deadlines.$inferSelect;
export type NewCachedDeadline = typeof deadlines.$inferInsert;
export type CachedNotification = typeof notifications.$inferSelect;
export type NewCachedNotification = typeof notifications.$inferInsert;
export type CachedApproval = typeof approvals.$inferSelect;
export type NewCachedApproval = typeof approvals.$inferInsert;
export type CachedDocument = typeof documents.$inferSelect;
export type NewCachedDocument = typeof documents.$inferInsert;
export type DocumentUpload = typeof documentUploads.$inferSelect;
export type NewDocumentUpload = typeof documentUploads.$inferInsert;
export type DocumentUploadFile = typeof documentUploadFiles.$inferSelect;
export type NewDocumentUploadFile = typeof documentUploadFiles.$inferInsert;
