/**
 * Data shape for the MTD client-summary PDF. Keep in sync with the
 * Salesforce-side MtdSummaryPdfService.buildPayload — anything you add here
 * needs adding there too.
 */

export type MtdBrandId = 'clever' | 'workwell';

export interface MtdSummaryTotals {
  totalIncome: number | null;
  totalExpenses: number | null;
  netProfit: number | null;
}

export interface MtdMonthRow {
  monthEnd: string | null; // 'yyyy-MM-dd'
  income: number | null;
  expense: number | null;
  profit: number | null;
}

export interface MtdSummaryIssue {
  title: string;
  detail: string;
}

export interface MtdSummaryData {
  kind: 'mtd';
  brandId: MtdBrandId;
  brandName: string;
  isDraft: boolean;

  client: {
    name: string;
    businessName?: string | null;
  };

  period: {
    quarter?: string | null;
    taxYear?: string | null;
    startDate: string; // 'yyyy-MM-dd'
    endDate: string;   // 'yyyy-MM-dd'
  };

  totals: MtdSummaryTotals;
  monthly: MtdMonthRow[];

  /**
   * Factual prompts auto-derived from the review (unreconciled counts,
   * duplicates, empty months, etc.). Empty when there's nothing to flag —
   * the PDF hides the section entirely in that case.
   */
  issues?: MtdSummaryIssue[];

  /**
   * Client-facing, fact-based narrative (trends vs prior month/quarter, gentle
   * suggestions from flags, sector note). Generated by the AI layer from data we
   * already hold — hidden when absent.
   */
  financialSummary?: string | null;

  verdict?: string | null;       // Pass / Refer / Fail (deterministic)
  humanVerdict?: string | null;  // Approved / etc.
  preparedAt: string;             // ISO datetime
}

const sampleClever: MtdSummaryData = {
  kind: 'mtd',
  brandId: 'clever',
  brandName: 'Clever Accounts',
  isDraft: true,
  client: { name: 'Megabites Sandwich Bar / Catering', businessName: 'Megabites' },
  period: {
    quarter: 'Q1',
    taxYear: '26/27',
    startDate: '2026-04-06',
    endDate: '2026-07-05',
  },
  totals: {
    totalIncome: 14214.42,
    totalExpenses: 504.59,
    netProfit: 13709.83,
  },
  monthly: [
    { monthEnd: '2026-05-05', income: 7817.59, expense: 354.87, profit: 7462.72 },
    { monthEnd: '2026-06-05', income: 6396.83, expense: 149.72, profit: 6247.11 },
    { monthEnd: '2026-07-05', income: 0, expense: 0, profit: 0 },
  ],
  issues: [
    {
      title: 'Unreconciled transactions',
      detail:
        '5 transactions in FreeAgent are still unreconciled. Most recent dated 2026-05-12.',
    },
    {
      title: 'Possible duplicates',
      detail:
        '2 transactions flagged by FreeAgent as a potential duplicate — worth a sense-check.',
    },
  ],
  financialSummary:
    'A strong quarter — income came in at £14,214.42, around 12% ahead of last quarter, and your latest month held steady on the one before. With costs kept low, you were left with a healthy profit.\n\n' +
    '- Income of £14,214.42, up about 12% on last quarter.\n' +
    '- Expenses of £504.59 leave a net profit of £13,709.83.\n' +
    '- A few odds and ends to tidy: 5 transactions still need reconciling, the most recent on 12 May.\n' +
    '- Nothing urgent — we can sort these together before the year-end review.',
  verdict: 'Pass',
  humanVerdict: null,
  preparedAt: '2026-06-22T13:00:00Z',
};

const sampleWorkwell: MtdSummaryData = {
  ...sampleClever,
  brandId: 'workwell',
  brandName: 'Workwell Accountancy',
  client: { name: 'Jake Dennison T/a Pendle Plumbing and Heating', businessName: 'Pendle Plumbing' },
};

export function buildSampleData(brand: MtdBrandId): MtdSummaryData {
  return brand === 'workwell' ? sampleWorkwell : sampleClever;
}
